### ISSUE TITLE
Avatar below footer

### ISSUE THREAD

**Issue by LunaGrown** [Dev49net/wp-first-letter-avatar#1]
Hi!
I like the plug-in and really this is not a big deal, however when signed in the avatar for whomever is signed in is moved to the lower left corner below the footer instead of up top in the dashboard as usual. Is there a way to rectify this? any help would be greatly appreciated.

Best Regards!

**Comment by Dev49net** [comment]
You're right, I never noticed it! It's quite obvious that it works that way - the filter is applied on the avatar output, so this includes the dashboard avatar, which is styled differently than the comment avatars. 
I just updated the plugin with new feature (round avatars). I'll try to find a workaround to this issue within couple of next days. There must be a nice way to make it right.
Thanks for the information.

**Comment by Dev49net** [comment]
This issue is now fixed. Current version on GitHub and WordPress plugin directory (https://wordpress.org/plugins/wp-first-letter-avatar/) now have this problem fixed.
Thanks @LunaGrown for noticing it!

**Comment by LunaGrown** [comment]
Daniel,

Perfect! Thank you kindly!

Best Regards

Chris
